### ISSUE TITLE
Terminal Setup

### ISSUE THREAD

**Issue by reintroducing** [elijahmanor/elijahmanor#2]
Hey Elijah,
Hope you don't mind me posting here but I'm combing through your GitHub after watching [this](https://elijahmanor.com/react-devtools-profiler/?utm_campaign=React%2BNewsletter&utm_medium=email&utm_source=React_Newsletter_132) and love your terminal setup. Mind sharing what you're using and theme? I was hoping to find it here but no such luck :)

**Comment by reintroducing** [comment]
And literally after posting this I found https://elijahmanor.com/uses/. Sorry for the noise :)

**Comment by elijahmanor** [comment]
Ha, no problem! Glad you found the resource. Enough people have asked me about it that I thought a page dedicated to answering would be helpful. If there is anything that I'm missing on that page, feel free to let me know. Thanks for coming by!
